### PR TITLE
Connectome stuff

### PR DESCRIPTION
**Pull request by bradenkatzman**
Most of this is implemented, minus whatever we decide to change or what isn't what Anthony was expecting. 

Sent an email titled: "Finishing Connectome" with more review of this and some finishing questions

### CODE REVIEW

**Comment by tangydoris** [comment]
Hey Braden,

Do all the old features work in this version? If you tested everything and nothing is broken, I will go ahead and merge your pull request. I am making a million changes to implement stories/notes right now so just let me know so I dont end up testing on a broken version!

Thanks,
Doris

Huiyao “Doris” Tang
New York University Class of 2017
BS Computer Science & Electrical Engineering
huiyao.tang@gmail.edu
http://www.aboutdoristang.com

**Comment by bradenkatzman** [comment]
Hey hey my version was working! I've also been keeping it synced, saw that
you're doing story stuff

If something doesn't work let me know and I'll check it out right
away. all of the rules, searching, and highlighting was working fine so I
think we're good!

**Comment by tangydoris** [comment]
Awesome, thanks! I will merge the pull request once I hit a good checkpoint.

**Comment by bradenkatzman** [comment]
Cool cool lemme know if I can help with anything

**Comment by tangydoris** [comment]
Did you make the SceneElement class so that a scene element object can represent either a billboard or a mesh?

**Comment by bradenkatzman** [comment]
Yes! I think there's a flag or something that indicates that it's a
billboard. I haven't looked in a bit but I can go through and clarify
anything there. Anything said ultimately a config file will have both
billboard scene elements and meshes

There's a field in the config that indicates a billboard

**Comment by bradenkatzman** [comment]
*Anthnony said

Great autocorrect haha

**Comment by tangydoris** [comment]
Are you talking about the story config file or the cellshapes config file?

**Comment by bradenkatzman** [comment]
Story config!

StoryList.java had a check for a billboard SceneElement or a mesh

**Comment by tangydoris** [comment]
Now is that the same as a scene element overlay or no? My main question is, what is the difference between a note with a .obj resource location and a billboard? My impression is that a billboard is just a 2D piece of text that transforms with the scene but it doesn’t have complicated geometry like a scene element/cell shape. 


This is a screenshot of the current story config file. I’m having trouble differentiating between the OVERLAY line with cow.obj and the BILLBOARD line.

If you don’t know for sure, no worries! I can always ask Anthony. But just wondering if you know since you began working on this first!

**Comment by bradenkatzman** [comment]
A billboard is a 3D block of text that is tied to a point and transforms
with the scene and the 2D overlays are like the time and nuclei count that
have a static location

I hadn't started on the 2D overlays when I stopped working on that so I'm
not sure how they are represented in the file

And I didn't see an image! Maybe text it to me and I can look at the config
file??

**Comment by tangydoris** [comment]
About to merge...will let you know if I run into any problems

**Pull request merged**
